### ISSUE TITLE
create user stories in discovery workshops

### ISSUE THREAD

**Issue by idabrogie** [idabrogie/produkt-api#16]
Vi genomför en discovery workshop och skriver userstories "as a user I want to..." och försöker oss på user story mappings?
https://cucumber.io/docs/bdd/

första steget i bdd
Discovery -> Forumation -> Automation

**Comment by fatimagrahn22** [comment]
Vi har haft mötet onsdag 29/5.

https://miro.com/app/board/uXjVKDyP-Hw=/
