### ISSUE TITLE
Webshop controll checkout form

### ISSUE THREAD

**Issue by phinds77** [idabrogie/produkt-api#17]
Som en användare vill jag kunna mata in uppgifter till fälten och få dessa validerade när användaren trycker på knappen "Continue to checkout".

Använd ett fake visakort nr 4242424242424242 med detta kort nr kan vilket expiredate användas som är senare än dagensdatum och vilken 3 siffrig CVV kod användas

Verktyg som ska användas är cucumber med selenium

https://webshop-agil-testautomatiserare.netlify.app/

**Comment by fatimagrahn22** [comment]
@idabrogie 

Gherkin:
Background: User wants to checkout shopcart
Given there are items in the shopcart
And the user is on Checkoutpage

Scenario: Form is missing data
When user does not fill in the form
And user clicks the continue to checkout-button
Then the user cannot continue to checkout

**Comment by idabrogie** [comment]
more gherkin:

Scenario: When user fills out the form correct

when the user fill out the form
and clicks on the contunei button
then no validation error should be seen
