### ISSUE TITLE
Webshop controll to add products to shopCart

### ISSUE THREAD

**Issue by phinds77** [idabrogie/produkt-api#18]
Som en användare vill jag kunna kontrollera att det går att lägga till varor till kundvagnen.
Testet är godkänt när varorna syns i varukorgen och att varukorgen inte är tom.
Verktyg som ska användas är cucumber med selenium
https://webshop-agil-testautomatiserare.netlify.app/

**Comment by fatimagrahn22** [comment]
Background
Given user is in the shop

Given the cart is empty
When user adds product to cart
Then the number of products should be 1

Given the cart has 1
When user adds product to cart
Then the number of products should be 2
